### ISSUE TITLE
care to contribute?

### ISSUE THREAD

**Issue by thebigredgeek** [GiladShoham/graphql-apollo-errors#1]
Hey Gilad,

Cool lib.  Would love your help contributing [here](https://github.com/thebigredgeek/apollo-errors) if you are down.

**Comment by GiladShoham** [comment]
@thebigredgeek 
I'll try to do my best, but maybe it will be better to corporate and merge both libraries?
I'll make the changes I have recommended on your repo, in my library.
Then maybe we can move some of your features here, so there will be only one package.
I think it's better to move everything here because it already contains more features and it has 100% tests coverage.

What do you think?

**Comment by thebigredgeek** [comment]
Hmm, not sure.  Currently working on v2 of apollo-errors which expands the functionality a bit while also keeping the surface area quite small, which was the intent to begin with.  A good number of people working with apollo already use apollo-errors, so probably not.
